#!/bin/bash
# 
# View audio file as a waveform.
# Display corresponding info from dr14.txt, loudness.txt,
# and some track info as overlay. Use local cache for speedup.
#
# dependencies: audiowaveform (https://github.com/bbcrd/audiowaveform)
#               exiftool
#               imagemagick
#               feh
#               vorbis-tools
#
# by ClixT, dev@clixt.net
# License: WTFPL
# This work is free. You can redistribute it and/or modify it under the
# terms of the Do What The Fuck You Want To Public License, Version 2,
# as published by Sam Hocevar. See http://www.wtfpl.net/ for more details.
#
################################################################################################
# full path to audiowaveform binary:
AUDIOWAVEFORM=$(which audiowaveform)
# audiowaveform x-axis resolution
PIXELS_PER_SECOND=5
# preview cache directory
CACHEDIR=~/.cache/audioview

if [ ! -x "$AUDIOWAVEFORM" ]; then
  echo "Error: audiowaveform not found"
  exit 1
fi
if [ ! -x "$(which exiftool)" ]; then
  echo "Error: exiftool not found"
  exit 1
fi
if [ ! -x "$(which convert)" ]; then
  echo "Error: imagemagick not found"
  exit 1
fi
if [ ! -x "$(which feh)" ]; then
  echo "Error: feh not found"
  exit 1
fi

if [ ! -d "$CACHEDIR" ]; then
  mkdir "$CACHEDIR"
  if [ ! -d "$CACHEDIR" ]; then
    echo "Error: cache $CACHEDIR cannot be created"
    exit 1
  fi
fi

SRCPATH=$(readlink -f "$1")
SRCDIR=$(dirname "$SRCPATH")
FNAME=$(echo -n "$SRCPATH" | sed 's/\\$/\\\\$/' | grep -Eo '[^/]+$')

# temp png image file
TEMPIMAGE=$(echo "$SRCPATH" | grep -Po '[^/]+/[^/]+$' | sed 's/\// - /' | sed 's/[^.]*$/png/')
TEMPIMAGE="$CACHEDIR/$TEMPIMAGE"

if [ ! -s "$TEMPIMAGE" ]; then
  # get file info
  FILEINFO=$(exiftool -S "$SRCPATH" 2>/dev/null)
  
  DURATION=$(echo "$FILEINFO" | grep -i -m 1 Duration:)
  if [[ $DURATION =~ ([0-9]+):([0-9]+):([0-9]+) ]]; then
    LENGTH=$(expr ${BASH_REMATCH[1]} \* 3600 + ${BASH_REMATCH[2]} \* 60 + ${BASH_REMATCH[3]} + 1)
  elif [[ $DURATION =~ ([0-9]+)\.[0-9]+.*s ]]; then
    LENGTH=$(expr ${BASH_REMATCH[1]} + 1)
  fi
  # check audio length
  if [[ -z $LENGTH ]]; then
    echo "Cannot determine length of audio file"
    exit 1
  fi
  # calculate required png width in pixels
  WIDTH=$(expr $LENGTH \* $PIXELS_PER_SECOND)
  
  # detect ogg and convert to wav (ogg support for audiowaveform)
  if [[ $(file "$SRCPATH" | grep -c "Vorbis audio") -eq 1 ]]; then
    AUDIOFILE=$TEMPIMAGE.wav
    oggdec -o "$AUDIOFILE" "$SRCPATH" 2>/dev/null
  else
    AUDIOFILE="$SRCPATH"
  fi
    
  # parse file info
  SIDE=$(echo "$FILEINFO" | grep -i -m 1 Side: | sed 's/.*:\s*//')
  BITRATE=$(echo "$FILEINFO" | grep -i -m 1 AudioBitrate: | sed 's/.*:\s*//')
  TRACKNR=$(echo "$FILEINFO" | grep -i -m 1 -E 'Track(N[^:]*r)?:' | sed 's/.*:\s*//' | sed 's/\/.*//')
  TRACKNAME=$(echo "$FILEINFO" | grep -i -m 1 Title: | sed 's/[^:]*:\s*//')
  ARTIST=$(echo "$FILEINFO" | grep -i -m 1 Artist: | sed 's/[^:]*:\s*//')
  ALBUM=$(echo "$FILEINFO" | grep -i -m 1 Album: | sed 's/[^:]*:\s*//')
  DATE=$(echo "$FILEINFO" | grep -i -m 1 -E '^Date(TimeOriginal)?:' | sed 's/.*:\s*//')
  YEAR=$(echo "$FILEINFO" | grep -i -m 1 -E '^Year:' | sed 's/.*:\s*//')
  if [ -z "$DATE" -a -n "$YEAR" ]; then
    DATE=$YEAR
  fi
  
  # define overlay data
  cd "$SRCDIR"
  LINE_META=$(echo -n "$ARTIST" | sed 's/\\$/\\\\$/')" - "$(echo -n "$ALBUM" | sed 's/\\$/\\\\$/')" ($DATE) - $SIDE$TRACKNR - "$(echo -n "$TRACKNAME" | sed 's/\\$/\\\\$/')
  LINE_EBU128=$(find -iname loudness.txt -exec sh -c "grep -o \".*$FNAME\" '{}' " \; | grep -Po '\S.*dBTP' | tr -s ' ')
  LINE_DR=$(find \( -iname dr14.txt -o -iname foo_dr.txt \) -exec sh -c "grep -E \"DR.*\s0?$TRACKNR\s*\-\" '{}' " \; | grep -Fi "$TRACKNAME" | grep -Po 'DR\d+' | head -n 1)
  
  # generate png file
  $AUDIOWAVEFORM -i "$AUDIOFILE" -o "$TEMPIMAGE" --pixels-per-second $PIXELS_PER_SECOND \
  -w $WIDTH -h 512 --compression 5 --background-color 000000 --border-color 996666 --axis-label-color BBBBBB
  
  # put overlay into png
  convert -pointsize 14 -fill white \
  -draw "text 10,456 '$LINE_META'" \
  -draw "text 10,473 '$LINE_EBU128'" \
  -draw "text 10,491 '$LINE_DR'" \
  -draw "text 10,508 '$BITRATE'" "$TEMPIMAGE" "$TEMPIMAGE"
  
  # clean up
  rm "$TEMPIMAGE"*wav 2>/dev/null
  
fi

# view waveform
feh --borderless --no-menus "$TEMPIMAGE" 2>/dev/null &

# delete old files from cache
find "$CACHEDIR" -maxdepth 1 -type f -mtime +30 -delete 2>/dev/null

exit 0
